version: '3'
services:
  tad:
    image: postgres
    container_name: 'postgres'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    ports:
      - ${DB_PORT}:5432
